# Generated by Django 4.2.1 on 2023-05-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='todo',
            name='ordering',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='todo',
            constraint=models.UniqueConstraint(fields=('board', 'ordering'), name='unique_ordering'),
        ),
    ]
