# Generated by Django 4.2.1 on 2023-05-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_todo_unique_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['ordering', 'pk']},
        ),
    ]
